import type { Receipt } from '@stockai/core';
export const demoReceipts: Receipt[] = [
  {
    id: 'r1',
    supplier: 'Verde Campo',
    category: 'Hortifruti',
    invoice: '008.421',
    unit: 'Jardins',
    date: '2026-09-18',
    time: '10:42',
    status: 'pending_approval',
    lines: [
      {
        id: 'tomate',
        name: 'Tomate italiano',
        uom: 'KG',
        invoiced: 24,
        counted: 20,
        priceCents: 890,
      },
      {
        id: 'alface',
        name: 'Alface americana',
        uom: 'UN',
        invoiced: 18,
        counted: 18,
        priceCents: 450,
      },
      { id: 'cebola', name: 'Cebola roxa', uom: 'KG', invoiced: 15, counted: 13, priceCents: 680 },
    ],
  },
  {
    id: 'r2',
    supplier: 'Frigorífico Prime',
    category: 'Proteínas',
    invoice: '012.305',
    unit: 'Jardins',
    date: '2026-09-18',
    time: '10:15',
    status: 'counting',
    lines: [
      { id: 'file', name: 'Filé mignon', uom: 'KG', invoiced: 20, counted: null, priceCents: 7990 },
      {
        id: 'frango',
        name: 'Peito de frango',
        uom: 'KG',
        invoiced: 30,
        counted: null,
        priceCents: 1890,
      },
    ],
  },
  {
    id: 'r3',
    supplier: 'Laticínios da Serra',
    category: 'Laticínios',
    invoice: '003.892',
    unit: 'Itaim',
    date: '2026-09-18',
    time: '09:48',
    status: 'closed',
    lines: [
      {
        id: 'manteiga',
        name: 'Manteiga sem sal',
        uom: 'KG',
        invoiced: 10,
        counted: 10,
        priceCents: 4200,
      },
      {
        id: 'creme',
        name: 'Creme de leite fresco',
        uom: 'L',
        invoiced: 12,
        counted: 12,
        priceCents: 2890,
      },
    ],
  },
  {
    id: 'r4',
    supplier: 'Mar & Costa',
    category: 'Pescados',
    invoice: '005.107',
    unit: 'Jardins',
    date: '2026-09-18',
    time: '09:20',
    status: 'pending_approval',
    lines: [
      {
        id: 'salmao',
        name: 'Salmão fresco',
        uom: 'KG',
        invoiced: 18,
        counted: 16.5,
        priceCents: 8490,
      },
    ],
  },
  {
    id: 'r5',
    supplier: 'Casa dos Grãos',
    category: 'Mercearia',
    invoice: '021.650',
    unit: 'Itaim',
    date: '2026-09-18',
    time: '08:55',
    status: 'closed',
    lines: [
      {
        id: 'arroz',
        name: 'Arroz arbóreo',
        uom: 'KG',
        invoiced: 25,
        counted: 25,
        priceCents: 2490,
      },
      {
        id: 'azeite',
        name: 'Azeite extravirgem',
        uom: 'L',
        invoiced: 10,
        counted: 10,
        priceCents: 5890,
      },
    ],
  },
  {
    id: 'r6',
    supplier: 'Verde Campo',
    category: 'Hortifruti',
    invoice: '008.402',
    unit: 'Itaim',
    date: '2026-09-17',
    time: '08:30',
    status: 'closed',
    lines: [
      {
        id: 'tomate',
        name: 'Tomate italiano',
        uom: 'KG',
        invoiced: 30,
        counted: 30,
        priceCents: 890,
      },
    ],
  },
  {
    id: 'r7',
    supplier: 'Frigorífico Prime',
    category: 'Proteínas',
    invoice: '012.290',
    unit: 'Jardins',
    date: '2026-09-16',
    time: '10:00',
    status: 'closed',
    lines: [
      { id: 'file', name: 'Filé mignon', uom: 'KG', invoiced: 22, counted: 22, priceCents: 7990 },
    ],
  },
  {
    id: 'r8',
    supplier: 'Casa dos Grãos',
    category: 'Mercearia',
    invoice: '021.601',
    unit: 'Jardins',
    date: '2026-09-15',
    time: '09:30',
    status: 'closed',
    lines: [
      {
        id: 'arroz',
        name: 'Arroz arbóreo',
        uom: 'KG',
        invoiced: 20,
        counted: 20,
        priceCents: 2490,
      },
    ],
  },
];
export const money = (cents: number) =>
  new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(cents / 100);
export const qty = (value: number) =>
  new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 4 }).format(value);
